# A makefile for building the PolySim program.
#
# 	make [all]     - makes everything.
# 	make test      - runs the tests.
# 	make TARGET    - makes the given target.
# 	make clean     - removes all files generated by make.

CC = g++
CFLAGS = -g -Wall -Wextra -std=c++0x
INCS = -I /usr/local/include
LIBS =
OUT = bin/polysim.exe
SHELL = /bin/bash

SRCS := $(shell find src -name '*.cpp')
OBJS := $(SRCS:src/%.cpp=obj/%.o)
	
.PHONY: clean test

all : $(OBJS)
	$(CC) $(CFLAGS) $(INCS) $(LIBS) $(OBJS) -o $(OUT)

test : $(OBJS)
	make -C test all
	bin/test.exe

obj/%.o : src/%.cpp
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) $(INCS) $(LIBS) -c $< -o $@

clean:
	rm -rf bin/*
	rm -rf obj/*
	make -C test clean

